// frontend/src/views/web/article.vue
<template>
  <div class="markdown">
    <MdPreview :modelValue="content" />
  </div>
</template>


<script setup lang="ts">
  import { ref } from 'vue';
  import { MdPreview } from 'md-editor-v3';
  import 'md-editor-v3/lib/style.css';
  import { getOneArticle } from '@/api/article';
  import { useRoute, useRouter } from 'vue-router'
  import { ElMessage } from 'element-plus'

  const route = useRoute()
  const router = useRouter()
  const content = ref('')



  getOneArticle(Number(route.params.id)).then(res => {
    content.value = res.data.data.content
    if(res.data.data.content == undefined) {
      router.push({path: '/404'})
    }
  }).catch(err => {
    ElMessage.warning("获取文章失败")
  })

</script>


<style scoped>
.markdown {
  display: flex;
  flex-direction: row;
  margin-left: 15%;
  margin-right: 15%;
  margin-top: 50px;
  margin-bottom: 50px;
  min-height: 800px;
}
</style>

// frontend/src/pages/Article.tsx
import { useNavigate, useParams } from 'react-router-dom';
import { GetOneArticle } from '../api/article';
import { useEffect, useState } from 'react';
import { MdPreview } from 'md-editor-rt';
import 'md-editor-rt/lib/preview.css';

interface ArticleData {
  id: number,
  author: number,
  image: number,
  title: string,
  content: string,
  creation: string,
  latest: string,
}


const Article = () => {

  const params = useParams()
  const navigate = useNavigate()

  const [article, setArticle] = useState<ArticleData>();

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await GetOneArticle(Number(params.id));
        if (res.data.code === 200) {
          setArticle(res.data.data)
        } else {
          navigate("/404")
        }
      } catch (_) {

      }
    }
    fetchData().then(() => {})
  }, [params, navigate])

  
  return (
    <div style={{width: '100vw', display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
      <MdPreview style={{width: '80vw', maxWidth: '800px'}} modelValue={article ? article.content: ""} />
    </div>
  );
}
  
export default Article;
