// frontend/src/views/web/register.vue
<template>

  <div class="admin-login">

    <span data-aos="fade-down" class="admin-item">你好 世界!</span>

    <el-input class="admin-item" v-model="nickname" placeholder="请输入昵称" clearable />

    <el-input class="admin-item" v-model="username" placeholder="请输入账号" clearable />

    <el-input
      class="admin-item"
      v-model="password"
      type="password"
      placeholder="请输入密码"
      show-password
    />
    <div class="admin-button">
      <el-button data-aos="fade-right" class="admin-item" style="width: 40%;" @click="back">返回</el-button>

      <el-button data-aos="fade-left" class="admin-item" style="width: 40%;" @click="register">注册</el-button>
    </div>
    
  </div>

  
</template>


<script setup lang="ts">
  import { ref } from 'vue'
  import { userLogin, userRegister } from '@/api/user'
  import { useRouter } from 'vue-router';
  import { ElMessage } from 'element-plus'

  const router = useRouter();

  const nickname = ref('')
  const username = ref('')
  const password = ref('')

  const register = () => {
    if (nickname.value == '') {
      ElMessage.warning('请输入昵称')
      return
    }
    if (username.value == '') {
      ElMessage.warning('请输入账号')
      return
    }

    if (password.value == '') {
      ElMessage.warning('请输入密码')
      return
    }

    userRegister(
      nickname.value,
      username.value,
      password.value
    ).then(res => {
      if (res.data.data == true) {
        ElMessage.info('注册成功')
        router.push({path: '/login'})
      } else {
        ElMessage.warning(res.data.msg)
      }
    })

  }

  const back = () => {
    router.push({path: '/login'})
  }

</script>


<style scoped>
.admin-login{
  display: flex;
  flex-direction: column;
  
  width: 500px;
  /* height: 309px; */

  
  margin: 0 auto;
  margin-top: 50px;
  align-items: center;
  justify-content: center;
}
.admin-item {
  text-align: center;
  width: 50%;
  margin-top: 40px;
  color: #909399;
}

.admin-button {
  text-align: center;
}
</style>

// frontend/src/views/Register.tsx
import { useState } from 'react';
import { UserRegister } from '../api/user';
import { Button, message } from "antd";
import { useNavigate } from "react-router-dom";
import './Register.css'

const Register = () => {
  const [nickname, setNickname] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate()

  const register = () => {
    if (nickname === '' || nickname.length > 16) {
      message.warning('昵称格式错误');
      return
    }
    if (username === '' || username.length > 16) {
      message.warning('账号格式错误');
      return
    }
    if (password === '' || password.length > 32) {
      message.warning('密码格式错误');
      return
    }
    UserRegister(nickname, username, password).then(res => {
      if (res.data.code === 200) {
        message.success("注册成功")
        navigate('/login')
      } else {
        message.warning(res.data.msg)
      }
     
    }).catch(_ => {
      message.error("网络原因注册失败")
    })
    
  }

  return (
    <div className="register-container">
      <span className="register-item">注册</span>
      <div className="register-input" >
        <input type="text" value={nickname} onChange={e => {setNickname(e.target.value)}} required />
        <label>昵称</label>
      </div>
      <div className="register-input" >
        <input type="text" value={username} onChange={e => {setUsername(e.target.value)}} required />
        <label>账号</label>
      </div>
      <div className="register-input" >
        <input type="password" value={password} onChange={e => {setPassword(e.target.value)}} required />
        <label>密码</label>
      </div>
      <div className="register-item">
        <Button style={{width: '80px'}} onClick={register}>注册</Button>
      </div>
    </div>
  )
}

export default Register;
